name: firt workflow
on: push
jobs:
    pushing:
        runs-on: ubuntu_latest
        steps:
            - name: pushing the code
              run: echo 'Pushing the code...'
            - name: ending pushing
              run: echo 'Your code is pushed.'
              